Repository ClairBerlin/clair-website, pull requests merged in 2020-11, with the labels that each got.

#14 Clarify intro
  _data/home.yml
Labels: documentation

#16 Added DIY article.
  _data/nav.yml
  _posts/2020-11-09-wie-alles-begann.md
  selbstbau-sensor.md
  technik.md
Labels: documentation

#18 Add share buttons
  _includes/share_buttons.html
  _layouts/post.html
  _site/feed.xml
  _site/presse/2020/11/24/pm-ist-die-luft-rein.html
  _site/sitemap.xml
  _site/technik/2020/11/09/wie-alles-begann.html
Labels: enhancement

#19 Fix share buttons
  _includes/share_buttons.html
  _site/datenschutz.html
  _site/faq.html
  _site/feed.xml
  _site/hintergrund.html
  _site/impressum.html
  _site/index.html
  _site/mitmachen.html
  _site/neuigkeiten.html
  _site/presse/2020/11/24/pm-ist-die-luft-rein.html
  _site/selbstbau-sensor.html
  _site/team.html
  _site/technik.html
  _site/technik/2020/11/09/wie-alles-begann.html
Labels: bug

#21 Replace link to mcs-design doc
  selbstbau-sensor.md
Labels: bug
